name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install -r requirements.txt
      - name: Lint with ruff
        run: |
          # Find major errors and point them out
          ruff --format=github --ignore=F401,F841,E501 --target-version=py37 .
          
          # Output all the non fatal issues
          ruff --quiet --format=github --select=F401,F841,E501 --target-version=py37 .
